# Generated by Django 4.2.2 on 2023-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=3)),
                ('name', models.CharField(default='', max_length=52)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Africa', 'Africa'), ('Oceania', 'Oceania'), ('Antarctica', 'Antarctica'), ('South America', 'South America')], default='Asia', max_length=20)),
                ('region', models.CharField(default='', max_length=26)),
                ('surfacesrea', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('indepyear', models.SmallIntegerField(default=None)),
                ('population', models.IntegerField(default=0)),
                ('lifeexpectancy', models.DecimalField(decimal_places=1, default=None, max_digits=3)),
                ('gnp', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('gnpold', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('localname', models.CharField(default='', max_length=45)),
                ('governmentform', models.CharField(default=None, max_length=45)),
                ('headofstate', models.CharField(default='', max_length=60)),
                ('capital', models.IntegerField(default=None)),
                ('Code2', models.CharField(default='', max_length=2)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(default='', max_length=3)),
                ('language', models.CharField(max_length=15)),
                ('continent', models.CharField(choices=[('T', 'T'), ('F', 'F')], default='F', max_length=10)),
                ('gnpold', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
            ],
            options={
                'db_table': 'countrylanguage',
            },
        ),
    ]
